### ISSUE TITLE
Add screenshots in readme  ?

### ISSUE THREAD

**Issue by sadortun** [Danamir/gitlab-userscripts#3]
Hi,

It would be nice to have a few screenshots in the readme to show the UI.

**Comment by Danamir** [comment]
There you go ! I added a SCREENS.md, and a link in the readme.

The screens are based on a random board selected on GitLab : https://gitlab.com/gitlab-org/gitlab-runner/boards , to make sure it works even with no custom labels.

**Comment by sadortun** [comment]
Awseome ! 

https://github.com/Danamir/gitlab-userscripts/commit/5b0f7dbd8265840e2da1bb5e7d4eb4a280d6550c#diff-1aaaf8971d91ea7f9a3fa1f291cdabf4
