### ISSUE TITLE
Script hase more than one wired behavior

### ISSUE THREAD

**Issue by Paebbels** [Danamir/gitlab-userscripts#4]
I installed both scripts in Tampermonkey.

1. The buttons "Swimlanes" and "description text" show up twice.
2. After clicking "Swimlanes" multiple times, it added more and more "Main board" expanders.  
   This was done by the left button, the right button has the correct behavior.

Here is a screenshot:  
[![image][1]][1]
(click to enlarge)

 [1]: https://user-images.githubusercontent.com/956109/40075423-8aa6cffe-587c-11e8-907a-5fee5ba94fda.png

**Comment by Danamir** [comment]
Should be ok with the new version.
